package model.pojos;
// Generated 15-abr-2017 19:52:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Categoria categoria;
     private Usuario usuario;
     private double salario;
     private Date fechaAlta;
     private Date fechaBaja;

    public Empleado() {
    }

	
    public Empleado(Categoria categoria, Usuario usuario, double salario, Date fechaAlta) {
        this.categoria = categoria;
        this.usuario = usuario;
        this.salario = salario;
        this.fechaAlta = fechaAlta;
    }
    public Empleado(Categoria categoria, Usuario usuario, double salario, Date fechaAlta, Date fechaBaja) {
       this.categoria = categoria;
       this.usuario = usuario;
       this.salario = salario;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }




}


