package model.pojos;
// Generated 15-abr-2017 19:52:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private Integer idsocio;
     private Usuario usuario;
     private Date fechaBaja;
     private float cuota;
     private String socioParticipa;

    public Socio() {
    }

	
    public Socio(Usuario usuario, float cuota) {
        this.usuario = usuario;
        this.cuota = cuota;
    }
    public Socio(Usuario usuario, Date fechaBaja, float cuota, String socioParticipa) {
       this.usuario = usuario;
       this.fechaBaja = fechaBaja;
       this.cuota = cuota;
       this.socioParticipa = socioParticipa;
    }
   
    public Integer getIdsocio() {
        return this.idsocio;
    }
    
    public void setIdsocio(Integer idsocio) {
        this.idsocio = idsocio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public float getCuota() {
        return this.cuota;
    }
    
    public void setCuota(float cuota) {
        this.cuota = cuota;
    }
    public String getSocioParticipa() {
        return this.socioParticipa;
    }
    
    public void setSocioParticipa(String socioParticipa) {
        this.socioParticipa = socioParticipa;
    }




}


