package Pojos;
// Generated 15-abr-2017 19:52:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private Integer idactividad;
     private Sala sala;
     private String descripcionActividad;
     private String actividad;
     private Date fecha;
     private Set participas = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(Sala sala, String descripcionActividad, String actividad, Date fecha) {
        this.sala = sala;
        this.descripcionActividad = descripcionActividad;
        this.actividad = actividad;
        this.fecha = fecha;
    }
    public Actividad(Sala sala, String descripcionActividad, String actividad, Date fecha, Set participas) {
       this.sala = sala;
       this.descripcionActividad = descripcionActividad;
       this.actividad = actividad;
       this.fecha = fecha;
       this.participas = participas;
    }
   
    public Integer getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(Integer idactividad) {
        this.idactividad = idactividad;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public String getDescripcionActividad() {
        return this.descripcionActividad;
    }
    
    public void setDescripcionActividad(String descripcionActividad) {
        this.descripcionActividad = descripcionActividad;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }




}


