package Pojos;
// Generated 15-abr-2017 19:52:22 by Hibernate Tools 4.3.1



/**
 * ParticipaId generated by hbm2java
 */
public class ParticipaId  implements java.io.Serializable {


     private int idparticipa;
     private String nifUser;
     private int actSuscrito;

    public ParticipaId() {
    }

    public ParticipaId(int idparticipa, String nifUser, int actSuscrito) {
       this.idparticipa = idparticipa;
       this.nifUser = nifUser;
       this.actSuscrito = actSuscrito;
    }
   
    public int getIdparticipa() {
        return this.idparticipa;
    }
    
    public void setIdparticipa(int idparticipa) {
        this.idparticipa = idparticipa;
    }
    public String getNifUser() {
        return this.nifUser;
    }
    
    public void setNifUser(String nifUser) {
        this.nifUser = nifUser;
    }
    public int getActSuscrito() {
        return this.actSuscrito;
    }
    
    public void setActSuscrito(int actSuscrito) {
        this.actSuscrito = actSuscrito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipaId) ) return false;
		 ParticipaId castOther = ( ParticipaId ) other; 
         
		 return (this.getIdparticipa()==castOther.getIdparticipa())
 && ( (this.getNifUser()==castOther.getNifUser()) || ( this.getNifUser()!=null && castOther.getNifUser()!=null && this.getNifUser().equals(castOther.getNifUser()) ) )
 && (this.getActSuscrito()==castOther.getActSuscrito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdparticipa();
         result = 37 * result + ( getNifUser() == null ? 0 : this.getNifUser().hashCode() );
         result = 37 * result + this.getActSuscrito();
         return result;
   }   


}


