package Pojos;
// Generated 15-abr-2017 19:52:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idnif;
     private String nombre;
     private String apellidos;
     private String telefono;
     private String direccion;
     private String poblacion;
     private String cp;
     private Date fechaAlta;
     private String mail;
     private Set socios = new HashSet(0);
     private Set empleados = new HashSet(0);
     private Set participas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String idnif, String nombre, String apellidos, String telefono, String direccion, String poblacion, String cp, Date fechaAlta, String mail) {
        this.idnif = idnif;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.direccion = direccion;
        this.poblacion = poblacion;
        this.cp = cp;
        this.fechaAlta = fechaAlta;
        this.mail = mail;
    }
    public Usuario(String idnif, String nombre, String apellidos, String telefono, String direccion, String poblacion, String cp, Date fechaAlta, String mail, Set socios, Set empleados, Set participas) {
       this.idnif = idnif;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.direccion = direccion;
       this.poblacion = poblacion;
       this.cp = cp;
       this.fechaAlta = fechaAlta;
       this.mail = mail;
       this.socios = socios;
       this.empleados = empleados;
       this.participas = participas;
    }
   
    public String getIdnif() {
        return this.idnif;
    }
    
    public void setIdnif(String idnif) {
        this.idnif = idnif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Set getSocios() {
        return this.socios;
    }
    
    public void setSocios(Set socios) {
        this.socios = socios;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }




}


